/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_chainfire_libcfsurface_SurfaceHost */

#ifndef _Included_eu_chainfire_libcfsurface_SurfaceHost
#define _Included_eu_chainfire_libcfsurface_SurfaceHost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_chainfire_libcfsurface_SurfaceHost
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_eu_chainfire_libcfsurface_SurfaceHost_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     eu_chainfire_libcfsurface_SurfaceHost
 * Method:    done
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_chainfire_libcfsurface_SurfaceHost_nativeDone
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
